version: '3.3'
services:

  web:
    build:
      context: ./web
    volumes:
      - ./web/src:/app/src
    ports:
      - '3000:3000'

  api:
    build:
      context: ./api
    volumes:
      - "./api/src:/app/src"
    ports:
      - "3001:3001"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ~/.mongo/db:/data/db