version: '3.3'
services:

  web:
    build:
      context: ./web
    volumes:
      - ./web/src:/web/src
    ports:
      - '3000:3000'
  api:
    build:
      context: ./api
    volumes:
      - "./api/src:/app/src"
    ports:
      - "3001:3001"